In [8]:
import numpy as np

In [9]:
#1~10사이의 홀수만 갖는 배열 생성
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [10]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [11]:
#1~10
c = np.arange(1, 11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#배열 c를 2줄 5칸으로 변형하시오
d = c.reshape(2,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
#d의 요소타입, 크기, 모양을 출력하시오
print(d.dtype)
print(d.size)
print(d[0].size)
print(d.shape)

int32
10
5
(2, 5)


In [16]:
h, w = d.shape
h, _ = d.shape
h

2

In [22]:
e = np.zeros((3,4), dtype=np.int32)#기본dtype=float64. 
e.dtype

dtype('int32')

In [23]:
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
f = np.eye(3,5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [25]:
g = np.random.rand(2,3)
g

array([[0.64790316, 0.7326427 , 0.70359528],
       [0.71043223, 0.15631084, 0.98315586]])

In [26]:
h = np.random.randint(10, size=(3,4))
h

array([[1, 8, 4, 1],
       [9, 8, 9, 9],
       [1, 0, 5, 6]])

In [27]:
a = np.array([[1,2,3],[4,5,6]])
b = a<5
b

array([[ True,  True,  True],
       [ True, False, False]])

In [29]:
c = a[b]
c

array([1, 2, 3, 4])

In [33]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])
c = np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [34]:
a = np.zeros((3,3), dtype=np.int8)
b = np.ones((3,3), dtype=np.int8)

In [35]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [36]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [37]:
np.vstack((a,b))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [38]:
np.hstack((a,b))

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]], dtype=int8)

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
res = a[3:8]
res

array([4, 5, 6, 7, 8])

In [41]:
res = a[3:]
res

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
res = a[:7]
res

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
res = a[:]
res

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a = np.array([1,2,3])
b = a[np.newaxis, :]
b

array([[1, 2, 3]])

In [45]:
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3]])

In [46]:
b = np.array([[1,2,3], [4,5,6]]) 

In [47]:
b[1,2]

6

In [48]:
b[0]

array([1, 2, 3])

In [49]:
b[0, 1:3]#0번줄의 1,2칸

array([2, 3])

In [50]:
b[1, :2]

array([4, 5])

In [51]:
b[:, 0]  #모든 줄의 0번칸 요소

array([1, 4])

In [52]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
c = a%2  # [1, 0, 1...]
c

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [53]:
b = a%2==0

In [54]:
b

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [56]:
a[b]

array([ 2,  4,  6,  8, 10])

In [58]:
x = a[a%2==0]
x

array([ 2,  4,  6,  8, 10])

In [59]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [60]:
a+b

array([[ 6,  8],
       [10, 12]])

In [61]:
#브로드 캐스팅
#a = np.array([[1,2], [3,4]])
c = np.array([11,12])
d = a+c
d

array([[12, 14],
       [14, 16]])

In [62]:
a = np.array([[1,2], [3,4]])
c = a+1
c

array([[2, 3],
       [4, 5]])

In [63]:
#a의 각 요소가 3보다 작은지 비교하여 불린값 반환
b = a<3  
b

array([[ True,  True],
       [False, False]])

In [64]:
a = np.array([[1,2], [3,4]])
a.sum(axis=0) #열별 합

array([4, 6])

In [65]:
a.sum(axis=1)

array([3, 7])

In [68]:
s = ['1,aaa,67,56,45', '2,bbb,67,56,45']
datas = []
for i in s:
    data = i.split(',')
    datas.append(data)
    
np_arr = np.array(datas)#numpy 배열로 변환


In [69]:
np_arr

array([['1', 'aaa', '67', '56', '45'],
       ['2', 'bbb', '67', '56', '45']], dtype='<U3')

In [78]:
f = open('untitled.txt', 'r')
datas = []
while True:
    s = f.readline()
    if s=='':
        break
    s = s.split('\n')[0]
    data = s.split(',')
    datas.append(data)
    
f.close()
np_arr = np.array(datas)

In [79]:
np_arr

array([['1', 'aaa', '67', '87', '56'],
       ['2', 'bbb', '65', '45', '34']], dtype='<U3')