# NumPy
데이터 처리에 사용되는 가장 대표적이고 기본적인 라이브러리.    
과학/수학적 연산을 쉽고 빠르게 하기 위한 함수를 제공하여 다차원 배열 데이터를 효율적으로 처리할 수 있다.

**NumPy 패키지 가져오기**

In [1]:
import numpy as np

## 1. 배열 생성

- np.array(seq_data) - 시퀀스 데이터로 numpy 배열 생성  
- np.arange(시작값, 끝값, 간격) - 범위를 지정해 numpy 배열 생성

**배열의 속성 확인 (ndarray.속성)**
- ndarray.ndim: 차원수 확인  
- ndarray.shape: 배열의 모양을 튜플형태로 반환. (행, 렬)  
- ndarray.size: 배열의 크기  
- ndarray.dtype: 요소의 타입  
- ndarray.itemsize: 요소 데이터타입의 크기 (ex>int32 => 32bit, 4byte)

In [2]:
a = [1,2,3,4]  #파이썬 리스트
print(a)
print(type(a))
print(type(a[0]))

[1, 2, 3, 4]
<class 'list'>
<class 'int'>


In [3]:
arr = np.array(a)  #넘파이 배열 생성자 np.array()
print(arr)
print(type(arr))
print(arr.dtype)  #dtype: 요소 타입 확인
print(arr.shape)  #shape: 배열의 모양 확인, (행,열) 확인

[1 2 3 4]
<class 'numpy.ndarray'>
int32
(4,)


In [4]:
arr2 = np.array([5,6,7,8])  #1차원배열
print(arr2)
print(arr2.dtype)
print(arr2.shape)

[5 6 7 8]
int32
(4,)


In [5]:
arr3 = np.array([[1,2,3], [4,5,6]])  #2차원배열
print(arr3)
print(arr3.dtype)
print(arr3.shape)
print(arr3.ndim)  #dim: dimension 차원 수 확인

[[1 2 3]
 [4 5 6]]
int32
(2, 3)
2


In [6]:
arr4 = np.arange(10)  #연속된 숫자를 생성하여 배열 생성. 0에서 시작
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr5 = np.arange(0, 10, 3)  #arrange(시작값, 끝값, 간격) - 0에서부터 10까지 간격을 3으로 갖는 배열 생성
print(arr5)

[0 3 6 9]


**.reshape(m,n) - 배열의 형태를 m x n 형태의 2차원 배열로 변경**

In [8]:
arr6 = np.arange(12)
print(arr6)
print(arr6.ndim)

arr6 = arr6.reshape(3,4)  #reshape(): 배열의 모양 변환
print(arr6)
print(arr6.ndim)  #모양에 따라 차원수도 바뀌었음을 확인가능

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


**np.linspace(시작값, 끝값, 개수) - 시작값부터 끝값까지 지정한 개수만큼 균일한 간격으로 나눠진 numpy 배열 생성**  
- 기본적으로 실수의 형태로 배열이 생성됨
- 개수를 지정하지 않으면 50개로 간주함


In [9]:
arr7 = np.linspace(1, 10, 4)
print(arr7)
print(arr7.dtype)

[ 1.  4.  7. 10.]
float64


In [10]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

## 연습
#### 1. 1~10 사이의 홀수만 갖는 배열 생성

In [11]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [12]:
b = np.arange(1, 10 , 2)
b

array([1, 3, 5, 7, 9])

In [13]:
c = np.linspace(1, 9, 5)
c

array([1., 3., 5., 7., 9.])

#### 2. 배열 d를 2줄 5칸으로 변형 하시오

In [14]:
d = np.arange(1, 11)
d = d.reshape(2, 5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### 3. d의 요소타입, 크기, 모양을 출력하시오

In [15]:
print(d.dtype)
print(d.size)
print(d[0].size)
print(d.shape)

int32
10
5
(2, 5)


-----------

### 특별한 형태의 배열 생성

**.zeros()**   
np.zeros(n) - 모든 원소가 0으로 초기화된 1차원 배열 생성  
np.zeros((m,n)) - 모든 원소가 0으로 초기화된 m x n 형태의 2차원 배열 생성

In [16]:
e = np.zeros((3,4))  #0으로 채워진 3줄 4칸 형태의 배열 생성 (기본 dtype = float64)
print(e.dtype)
e

float64


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
f = np.zeros((3,4), dtype=np.int32)  #dtype을 int로 변환
print(f.dtype)

int32


**.ones()**  
np.ones(n) - 모든 원소가 1로 초기화된 1차원 배열 생성  
np.ones((m,n)) - 모든 원소가 1로 초기화된 m x n 형태의 2차원 배열 생성

In [18]:
np.ones((3,4), dtype=np.int16)  #1로 채워진 3줄 4칸 형태의 정수 배열 생성

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

**.empty()**  
np.empty(n) - 특정한 값으로 초기화되지 않은 1차원 배열 생성  
np.empty((n,m)) - 특정한 값으로 초기화되지 않은 m x n 형태의 2차원 배열 생성  
np.empty_like(배열) - 입력한 배열의 크기와 동일하며 특정한 값으로 초기화되지 않은 배열 생성  

'초기화되지 않은': 난수와 다른 임의의 값이 들어가며 값은 메모리에 저장된 내용에 따라 달라진다

In [19]:
np.empty([6,6]) #초기화되지 않은 값으로 배열 생성. 메모리도 초기화가 되어있지 않기때문에 예상치 못한 값들이 들어가있다

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**.full()**  
np.full(모양, 값) - 모든 값을 입력한 값으로 초기화한 배열을 모양대로 생성

In [20]:
np.full((2,3), 10, dtype=np.int32)  #full(모양, 값): 모든 값을 full 값으로 초기화

array([[10, 10, 10],
       [10, 10, 10]])

**난수 배열의 생성**  
np.random.rand() - 실수 난수를 요소로 갖는 배열 생성  
np.random.randint(최소값, 최대값, 모양) - 정수 난수를 요소로 갖는 배열 생성

In [21]:
np.random.rand(2,3)  #랜덤 값으로 배열 생성

array([[0.33215907, 0.58658376, 0.55891953],
       [0.66024227, 0.43841385, 0.29468849]])

In [22]:
np.random.randint(10, size=(3,4))  #0~9 사이의 정수를 사용한 랜덤값으로 이루어진 3x4 배열 생성

array([[0, 3, 4, 0],
       [7, 7, 0, 7],
       [6, 0, 2, 0]])

**단위행렬(identity matrix)**  
n x n인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬
- .identity(n)
- .eye(n) 또는 .eye(n, m, k=x)


In [23]:
np.identity(4)  #n x n행으로 이루어진 단위행렬(identity matrix)을 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(4)  #identity(n)와 마찬가지로 단위행렬을 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(3,5)  #다른점은 n x m 으로도 생성이 가능하다는 점

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.eye(3,5, k=2)  #k는 쉬프트 옵션. 오른쪽으로 쉬프트는 양수, 왼쪽으로 쉬프트는 음수

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**배열의 데이터 타입 변환**  

numpy 배열은 하나의 자료형만 가질 수 있다. 문자와 숫자가 섞여있을 경우 더 큰 데이터 타입인 문자로 통일된다.

요소 타입:  
	bool / int8,  int16,  int32,  int64 / uint8,  uint16,  uint32,  uint64 /  
	float16,  float32,  float64 /  complex64, complex128 / string_

- int, uint 모두 정수를 담는 타입
   - uint: unsigned int - 부호가 없다 = 양수를 표현
   - int8: 8비트 정수 (음수 128부터 양수 127까지, 총 256가지 숫자 표현)
   - uint8: 8비트 양수 (숫자 0부터 255까지 표현)
   
- float(실수)는 부호가 필수여서 unsigned 형태가 없다  


- .astype(dtype) - 지정한 타입으로 요소의 데이터 타입 변환
  - 실수를 정수로, 문자를 실수로 바꿀 수도 있다
  - 실수를 정수로 바꾸는 경우 소수점은 모두 내린다

In [27]:
arr8 = np.array(['1.1','2.2','3.3','4.4'])
print(arr8.dtype) #dtype <U3 은 최대 3개의 철자를 가진 유니코드 문자열을 의미

<U3


In [28]:
arr8.astype(float)  #astype(): 타입변환

array([1.1, 2.2, 3.3, 4.4])

## 2. 배열 처리 함수

- .sort() - 배열의 요소를 정리
- .concatenate() - 배열 결합
- .vstack() - 배열을 세로로 결합
- .hstack() - 배열을 가로로 결합
- .shape - 배열의 모양 출력

In [29]:
a = np.array([6,3,8,5,1,9,2])
print(np.sort(a))  #배열 안의 값을 오름차순으로 정리


b = np.array([11,22,33])
print(np.concatenate((a, b)))  #두 배열을 결합

[1 2 3 5 6 8 9]
[ 6  3  8  5  1  9  2 11 22 33]


In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

print(np.vstack((a, b)))  #두 배열을 세로로(vertical) 병합  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
np.hstack((a,b))  #두 배열을 가로로(horizontal) 병합

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

np.concatenate((a,b))  #2차원 배열끼리 concatenate로 결합하면 vstack과 같은 결과를 보여준다

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
a= np.arange(12)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [34]:
b=a.reshape(3,4)
print(b.shape)

(3, 4)


## 3. 배열 요소 접근과 인덱싱 및 슬라이싱

In [35]:
a = np.array([1,2,3,4,5,6,7,8])

b = a[np.newaxis, 2:6]  # 새로운 행의 값으로 2번째부터 6번째까지 칸의 값을 추가
print(b.shape)
print(b)

(1, 4)
[[3 4 5 6]]


In [36]:
b = a[np.newaxis, :]  # 새로운 행의 값으로 배열 전체를 추가
print(b.shape)
print(b)

(1, 8)
[[1 2 3 4 5 6 7 8]]


In [37]:
b = a[:, np.newaxis]  # 배열전체의 값을 새로운 행으로 만들어서 각 칸의 값으로 추가
print(b.shape)
print(b)

(8, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [38]:
#1차원 배열의 인덱싱
a = np.array([1,2,3,4,5])
a[3]#인덱싱. 

4

In [39]:
#2차원 배열의 인덱싱
b = np.array([[1,2,3], [4,5,6]])
b[0, 1]# 0번 줄의 1번칸 요소 = b[0][1] = 2 
b[0]  # 0번 줄의 요소 = [1,2,3]
b[1, 1:] # 1번줄의 1번칸부터 모든요소 = [5,6]
b[:, 0] # 모든 줄의 0번칸 요소 = [1, 4]
b[:, 0][:, np.newaxis] # 모든 줄의 0번칸 요소를 새로운 행으로 해서 각 칸에 추가 = [[1],[4]]

array([[1],
       [4]])

In [40]:
a[1:3]  #슬라이싱

array([2, 3])

In [41]:
a[a>3]  #배열 a의 요소 중 3보다 큰 요소만 추출. 요소에 대한 조건 수식을 작성하면 그 수식을 만족하는 요소만 추출해서 반환

array([4, 5])

In [42]:
a[a%2==0]  #a배열의 요소 중에서 짝수만 반환

array([2, 4])

In [43]:
a = np.array([1,2,3,4,5,6])
b = np.array([True, False, True, False, True, False])
c = a[b] #배열 b를 인덱스로 사용, True인 값만 추출
c

array([1, 3, 5])

In [44]:
a = np.array([1,2,3,4,5,6])
b = np.array([0,1,1,3,3,5]) #배열 b를 인덱스로 사용
c = a[b]  # c = [a[0], a[1], a[1], a[3], a[3], a[5]] = [1,2,2,4,4,6]
c

array([1, 2, 2, 4, 4, 6])

## 4. 배열끼리 연산  
#### => +, -, *, / : 배열의 동일한 요소마다 연산 수행

In [45]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,12,13],[14,15,16]])
a+b  # [[1+11, 2+12, 3+13], [4+14, 5+15, 6+16]]

array([[12, 14, 16],
       [18, 20, 22]])

In [46]:
a-b

array([[-10, -10, -10],
       [-10, -10, -10]])

In [47]:
a*b

array([[11, 24, 39],
       [56, 75, 96]])

In [48]:
a/b

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ]])

In [49]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([11,12,13])
a+b  # [[1+11, 2+12, 3+13], [4+11, 5+12, 6+13]]

#b가 [[10,11,12],[10,11,12]]으로 확장하여 계산. 브로드 캐스팅

array([[12, 14, 16],
       [15, 17, 19]])

In [50]:
d = np.array([[1,0],[0,1],[1,0]])
a@d  #행과 열을 곱한다


#  [[1,2,3],     [[1,0]
#   [4,5,6]]  X   [0,1]
#                 [1,0]]
#
#  = [[ (1*1)+(2*0)+(3*1), (1*0)+(2*1)+(3*0) ], 
#     [ (4*1)+(5*0)+(6*1), (4*0)+(5*1)+(6*0) ]]

array([[ 4,  2],
       [10,  5]])

In [51]:
a.dot(d)

array([[ 4,  2],
       [10,  5]])

## 5. 배열과 숫자 연산. +,-,*, **, / ....=> 배열 각 요소에 숫자와 연산

In [52]:
a=np.array([[1,2,3],[4,5,6]])
a*10

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
b=a<5  #배열 각 요소와 비교 연산한 결과인 bool 값을 요소로 하는 배열 반환
b

array([[ True,  True,  True],
       [ True, False, False]])

In [54]:
a[b]  #조건을 만족하는 배열 요소만 추출하여 배열로 반환

array([1, 2, 3, 4])

## 6. 논리 연산  
#### 각 요소끼리 연산하여 bool 결과들을 배열로 반환

In [55]:
a=np.array([1,2,3,4])
b=np.array([4,2,2,4])
a==b

array([False,  True, False,  True])

In [56]:
a>=b

array([False,  True,  True,  True])

In [57]:
np.all(a==b)  #모든 요소가 조건을 만족해야 True, 아니면 False

False

In [58]:
sum(a<3)  #조건을 만족하는 요소의 개수

2

In [59]:
a<3

array([ True,  True, False, False])

#### *np.logical_and():and 연산함수  
#### *np.logical_or():or 연산 함수  

In [60]:
np.logical_and(True, False)  #True and False = False

False

In [91]:
np.logical_and([True, False],[True, False])  # 같은 위치 조건 둘다 True 여야만 True

array([ True, False])

In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
np.logical_and(a>1, a<4)

array([False, False,  True,  True, False])

In [64]:
np.logical_or(True, False)

True

In [65]:
np.logical_or([True, False],[False, False])  #같은 위치 조건 둘 중 하나만 True 여도 True

array([ True, False])

In [66]:
np.logical_or(a<1, a>3)

array([ True, False, False, False,  True])

#### *np.where(조건, 참일때실행, 거짓일때실행)

In [67]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.where(a<5, a, a*10)  #a가 5보다 작을 때, 조건을 만족하면 a 그대로 쓰고, 조건을 만족하지 않으면 a*10 사용

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [69]:
a = np.array([[0,1,2],[0,2,4],[0,3,6]])
a

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [70]:
np.where(a<4, a, -1)

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [71]:
a=np.array([1,2,3,4,5])
b=np.array([11,12,13,14,15])
np.where([True, False, True, True, False], a, b)

array([ 1, 12,  3,  4, 15])

In [72]:
np.where([[True,False],[True, True]],[[1,2],[3,4]],[[5,6],[7,8]]) #배열에서 같은 위치에 있는 값을 조건에 따라 사용

array([[1, 6],
       [3, 4]])

## 7. 차원 변경  
#### *np.reshape(행,렬)

In [73]:
a=np.arange(12)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

*np.ravel(), np.flatten() => 배열을 1차원으로 변경

In [75]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

*np.newaxis => 요소를 새 축으로 만듬

In [78]:
c = a[:, np.newaxis]
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [79]:
c = b[:, np.newaxis]
c

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

8. 차원 연관 함수

차수  
axis=0 => x축 . 열별리 연산
axis=1 => y축 . 행별로 연산
axis=2 => z축
axis=-1  => 마지막 축(2차원:y축, 3차원:z축)

In [80]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
a.sum()#모든 요소의 합

21

In [82]:
a.sum(axis=0)#열별로 합

array([5, 7, 9])

In [83]:
a.sum(axis=1)#행별로 합

array([ 6, 15])

In [84]:
a.max()#a배열 모든 요소에서 최대값

6

In [85]:
a.max(axis=0)#열별로 최대값

array([4, 5, 6])

In [86]:
a.max(axis=1)#행별로 최대값

array([3, 6])

*argmax() / argmin() => 최대, 최소 값의 위치 반환

In [87]:
a.argmax()

5

In [88]:
a.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [89]:
a.argmax(axis=1)

array([2, 2], dtype=int64)