In [2]:
import cv2
import numpy as np

mode = True#검정
points = []

back = np.ones((512, 512), dtype=np.uint8)*255 
for i in range(50, 510, 100):
    back = cv2.line(back, (i,0), (i,511), (0,0,0), 2)
    back = cv2.line(back, (0,i), (511,i), (0,0,0), 2)

    
def makeXY(num):
    num1 = num//100
    num2 = num%100
    num3 = num2-50
    if -50<=num3<=50:
        p = num1*100+50
        return p

def draw_circle(event, x, y, flags, param):
    global mode
    x_ = makeXY(x)
    y_ = makeXY(y)
    if x_==None or y_==None:
        print('정확한 위치를 클릭하시오')
        return
    if event == cv2.EVENT_LBUTTONDOWN:
        c = 255 #바둑알 색. 흰색
        if mode:
            c = 0 #검정색
        
        if (x_, y_) in points:
            print('이미 놓은 자리다. 취소됨')
            return
        
        mode = not mode
        cv2.circle(back,(x_,y_), 20,(c,c,c),-1)
        
        if mode:#바둑알이 흰색일 때
            cv2.circle(back,(x_,y_), 21,(0,0,0),2)
           
        points.append((x_, y_))
        cv2.imshow('back', back)

cv2.namedWindow('back')
cv2.setMouseCallback('back', draw_circle)
cv2.imshow('back', back)

cv2.waitKey(0)   #키보드 입력 대기. 입력한 키값 반환
cv2.destroyAllWindows()  

이미 놓은 자리다. 취소됨
이미 놓은 자리다. 취소됨
이미 놓은 자리다. 취소됨
이미 놓은 자리다. 취소됨
이미 놓은 자리다. 취소됨
이미 놓은 자리다. 취소됨


In [40]:
num = 201
num1 = num//100
num2 = num-num1*100
num3 = num2-50
if -49<=num3<=50:
    num = num1*100+50
    
num

250

In [1]:
import cv2
import numpy as np

img = cv2.imread('a.jpg', cv2.IMREAD_COLOR)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np

img_gray = cv2.imread('a.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('img', img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#그레이 스케일 이미지 파일로 저장. a_gray.jpg
cv2.imwrite('a_gray.jpg', img_gray)
img = cv2.imread('a_gray.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img.shape

(427, 640)

In [24]:
#이미지 일부 추출
import cv2
import numpy as np

arr = [0]*3
img = cv2.imread('a.jpg', cv2.IMREAD_COLOR)
h, w, _ = img.shape

for i in range(0, 3):
    arr[i] = img[0:h, i*w//3:(i+1)*w//3]
    
for i in range(0, 3):   
    cv2.imshow('img'+str(i), arr[i])
    
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
#이미지 특정 채널(b, g, r) 추출

import cv2
import numpy as np

img = cv2.imread('a.jpg', cv2.IMREAD_COLOR)
img

array([[[ 87, 122, 135],
        [ 88, 123, 136],
        [ 88, 123, 136],
        ...,
        [ 76, 100, 112],
        [ 74, 100, 114],
        [ 74, 100, 114]],

       [[ 88, 123, 136],
        [ 87, 122, 135],
        [ 87, 122, 135],
        ...,
        [ 77, 103, 115],
        [ 76, 102, 116],
        [ 75, 101, 115]],

       [[ 85, 120, 133],
        [ 84, 119, 132],
        [ 83, 119, 129],
        ...,
        [ 77, 103, 117],
        [ 76, 102, 116],
        [ 75, 102, 116]],

       ...,

       [[120, 101,  96],
        [120, 101,  96],
        [119, 100,  95],
        ...,
        [ 84,  65,  58],
        [ 86,  67,  60],
        [ 88,  69,  62]],

       [[120, 101,  96],
        [120, 101,  96],
        [119, 100,  95],
        ...,
        [ 84,  65,  58],
        [ 87,  68,  61],
        [ 88,  69,  62]],

       [[121, 101,  96],
        [121, 101,  96],
        [120, 100,  95],
        ...,
        [ 85,  66,  59],
        [ 87,  68,  61],
        [ 89,  70,  63]]

In [21]:
b = img[:,:, 0]#blue
b

array([[ 87,  88,  88, ...,  76,  74,  74],
       [ 88,  87,  87, ...,  77,  76,  75],
       [ 85,  84,  83, ...,  77,  76,  75],
       ...,
       [120, 120, 119, ...,  84,  86,  88],
       [120, 120, 119, ...,  84,  87,  88],
       [121, 121, 120, ...,  85,  87,  89]], dtype=uint8)

In [23]:
g = img[:,:, 1]#green
g

array([[122, 123, 123, ..., 100, 100, 100],
       [123, 122, 122, ..., 103, 102, 101],
       [120, 119, 119, ..., 103, 102, 102],
       ...,
       [101, 101, 100, ...,  65,  67,  69],
       [101, 101, 100, ...,  65,  68,  69],
       [101, 101, 100, ...,  66,  68,  70]], dtype=uint8)

In [30]:
r = img[:,:, 2]#red
r

array([[135, 136, 136, ..., 112, 114, 114],
       [136, 135, 135, ..., 115, 116, 115],
       [133, 132, 129, ..., 117, 116, 116],
       ...,
       [ 96,  96,  95, ...,  58,  60,  62],
       [ 96,  96,  95, ...,  58,  61,  62],
       [ 96,  96,  95, ...,  59,  61,  63]], dtype=uint8)

In [1]:
h, w, _ = img.shape
img0 = np.zeros((h, w, 3), dtype=np.uint8)
img0[:,:, 2]=r
img0

NameError: name 'img' is not defined

In [32]:
cv2.imshow('img0', img0)
    
cv2.waitKey(0)
cv2.destroyAllWindows()